# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.FloatField(verbose_name='振幅')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '数据',
                'verbose_name_plural': '数据',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('workshop', models.IntegerField(default=1, verbose_name='车间')),
                ('seat', models.IntegerField(default=1, verbose_name='机位')),
                ('abline', models.CharField(choices=[('A', 'A线'), ('B', 'B线')], max_length=1, verbose_name='AB线')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('remarks', models.TextField(verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='测点编号')),
                ('level', models.IntegerField(default=1, verbose_name='级数')),
                ('direction', models.CharField(choices=[('v', '垂直'), ('a', '轴向'), ('r', '径向')], max_length=1, verbose_name='方向')),
                ('warning_line', models.FloatField(verbose_name='警告线')),
                ('danger_line', models.FloatField(verbose_name='危险线')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment')),
            ],
            options={
                'verbose_name': '测点',
                'verbose_name_plural': '测点',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment'),
        ),
        migrations.AddField(
            model_name='data',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Point'),
        ),
    ]
