# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='x坐标')),
                ('y', models.FloatField(verbose_name='y坐标')),
            ],
            options={
                'verbose_name': '数据',
                'verbose_name_plural': '数据',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('point_number', models.IntegerField(default=1, verbose_name='测点数')),
                ('seat', models.IntegerField(default=1, verbose_name='机位')),
                ('device', models.CharField(max_length=30, verbose_name='装置')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipment'),
        ),
    ]
